[theme]
primaryColor = "#6C63FF"  # Un violeta suave (tipo psicolog√≠a/creatividad)
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
headless = true